version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: utube
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nestjs:
    image: nestjs-app:latest
    build: .    
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    environment:
      TYPE_DB: postgres
      HOST_DB: postgres
      USER_DB: postgres
      PASS_DB: password
      NAME_DB: utube
      PORT_DB: 5432
    volumes:
      - .:/app

volumes:
  postgres_data:
